[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \ 'colorscheme' : 'wombat',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
  \ },
  \ 'component_function': {
  \   'gitbranch': 'fugitive#head'
  \ }
\ }
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
    \ '_' : {
        \ 'runner' : 'vimproc',
        \ 'runner/vimproc/updatetime' : 40,
        \ 'outputter' : 'error',
        \ 'outputter/error/success' : 'buffer',
        \ 'outputter/error/error' : 'quickfix',
        \ 'outputter/buffer/split' : ':botright 8sp',
        \ }
    \}
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#ctags_auto_gen = 1
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
# hook_add = "let g:previm_open_cmd = 'open -a google-chrome'"

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
  let lexima_ctrlh_as_backspace = 1
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
    let g:ackprg = 'ag --vimgrep'
'''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'mtakezawa0522/nerdtree-ag'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  nnoremap [coc] <Nop>
  nmap <space>c [coc]
  nmap <silent> [coc]f <Plug>(coc-format)
  nmap <silent> [coc]<space> :<C-u>CocList<cr>
  nmap <silent> [coc]rn <Plug>(coc-rename)
  nmap <silent> [coc]h :<C-u>call CocAction('doHover')<cr>
  nmap <silent> [coc]d <Plug>(coc-definition)
  nmap <silent> [coc]rf <Plug>(coc-references)
'''

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
  let g:vim_vue_plugin_load_full_syntax = 1
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
  nnoremap [fzf] <Nop>
  nmap <space>f [fzf]
  nmap <silent> [fzf]b :<C-u>Buffers<cr>
  nmap <silent> [fzf]h :<C-u>History<cr>
  nmap <silent> [fzf]g :<C-u>GFiles<cr>
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html', 'vue']

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'sharat87/roast.vim'
